global:
  scrape_interval: 15s # Match Tempo's metrics flush interval
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '.*duration_bucket.*'
        action: keep
    params:
      enable_exemplars: ['true']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
    metrics_path: '/metrics'
