server:
  http_listen_port: 3200 # Grafana connection port

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317 # OTLP gRPC receiver

metrics_generator:
  processor:
    service_graphs:
      dimensions: ['service.name', 'http.method', 'http.status_code']
    span_metrics:
      dimensions: ['service.name', 'status_code']
      histogram_buckets: [0.002, 0.004, 0.008, 0.016, 0.032, 0.064, 0.128, 0.256, 0.512, 1.024]

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks
