services:
  otel-collector:
    image: otel/opentelemetry-collector:0.70.0
    command: ['--config=/etc/otel-collector-config.yml']
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP HTTP receiver
      - '8888:8888' # Prometheus metrics exposed by the collector
      - '8889:8889' # Prometheus exporter metrics
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.41.0
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:9.3.6
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - '3000:3000'

  loki:
    image: grafana/loki:2.7.3
    volumes:
      - ./config/loki-config.yml:/etc/loki/loki-config.yml
      - ./data/loki:/loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/loki-config.yml

  tempo:
    image: grafana/tempo:2.0.1
    command: ['-config.file=/etc/tempo.yml']
    volumes:
      - ./config/tempo.yml:/etc/tempo.yml
      - ./data/tempo:/tmp/tempo
    ports:
      - '3200:3200' # tempo
      - '4317' # otlp grpc

networks:
  default:
    name: otel-network
