services:
  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
      - '13333:8001'
    environment:
      - REDIS_ARGS=--loglevel warning --save 60 1000 --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - cache-network

networks:
  cache-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/redis
