version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ['--config=/etc/otel-collector-config.yml']
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - '4317:4317' # OTLP gRPC (external exposure)
      - '4318:4318' # OTLP HTTP (external exposure)
    networks:
      - otel-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    networks:
      - otel-network

  grafana:
    image: grafana/grafana
    volumes:
      - ./config/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./data/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
    ports:
      - '3000:3000' # Grafana UI
    networks:
      - otel-network

  loki:
    image: grafana/loki:latest
    volumes:
      - ./config/loki-config.yml:/etc/loki/local-config.yml
      - ./data/loki:/loki
    command: -config.file=/etc/loki/local-config.yml
    networks:
      - otel-network

  tempo:
    image: grafana/tempo:latest
    volumes:
      - ./config/tempo-config.yml:/etc/tempo-config.yml
      - ./data/tempo:/tmp/tempo
    command: ['-config.file=/etc/tempo-config.yml']
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge
